import { IChromeRepository } from "../service/chrome.interface";
export class MockChromeRepository implements IChromeRepository {
  async getAllSpanText(): Promise<string[]> {
    // https://www.linkedin.com/in/nopd/details/experience/ 에서 발췌
    return Promise.resolve([
      "검색으로 가기",
      "주요 항목으로 건너뛰기",
      "메뉴 닫기",
      "새로운 업데이트 알림",
      "홈",
      "인맥",
      "채용공고",
      "메시지",
      "알림",
      "\n      상태 - 오프라인\n      ",
      "메시지",
      "1촌 맺기",
      "LINE Plus Corp",
      "4년 9개월",
      "Service Enablement Engineer",
      "2019년 2월 - 현재 · 3년",
      "미디어 모두 보기 5",
      "Site Reliability Engineer",
      "2017년 5월 - 2019년 1월 · 1년 9개월",
      "Seongnam, Gyeonggi-do, Korea",
      "Akamai Technologies",
      "4년",
      "Engagement Manager",
      "2016년 5월 - 2017년 5월 · 1년 1개월",
      "Gangnam-gu, Seoul, Korea",
      "2015년 12월 - 2017년 5월 · 1년 6개월",
      "Seoul, Korea",
      "Technical Project Manager II",
      "2015년 1월 - 2015년 11월 · 11개월",
      "Gangnam-gu, Seoul, Korea",
      "Solution Architect II",
      "2013년 6월 - 2014년 12월 · 1년 7개월",
      "Gangnam-gu, Seoul, Korea",
      "Technical Writer (External)",
      "Venture Square",
      "2014년 1월 - 2017년 4월 · 3년 4개월",
      "Seoul",
      "NoPD - VentureSquare",
      "Pedium",
      "2014년 12월 - 2015년 8월 · 9개월",
      "Manager",
      "SK Telecom",
      "2011년 10월 - 2013년 5월 · 1년 8개월",
      "Jung-gu, Seoul, Korea",
      "Software Engineer",
      "Samsung SDS",
      "2010년 1월 - 2011년 10월 · 1년 10개월",
      "Gangnam-gu, Seoul, Korea",
      "Software Engineer",
      "Samsung Networks",
      "2004년 1월 - 2009년 12월 · 6년",
      "Gangnam-gu, Seoul, Korea",
      "삼성전자, Global ERP 가동",
      '삼성전자 "해외A/S 만족도 PDA로 높인다"',
      "상태 - 온라인",
      "메시지",
      "메시지 쓰기",
    ]);
  }
}
